### ISSUE TITLE
Updating the version crash the UIs

### ISSUE THREAD

**Issue by lounice** [ashleykleynhans/stable-diffusion-docker#12]
Hi Ashleykleynhans,

I noticed that everytime I update the version of the image (ex 1.7.9 to 1.8.4), the UIs have errors; nothing in the container log, but in the logs of the different apps : 

`
# tail -f workspace/logs/webui.log 
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/launch.py", line 39, in <module>
    main()
  File "/workspace/stable-diffusion-webui/launch.py", line 35, in main
    start()
  File "/workspace/stable-diffusion-webui/modules/launch_utils.py", line 390, in start
    import webui
  File "/workspace/stable-diffusion-webui/webui.py", line 14, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'`

`
# tail -f workspace/logs/kohya_ss.log 
Traceback (most recent call last):
  File "/workspace/kohya_ss/setup/validate_requirements.py", line 19, in <module>
    from library.custom_logging import setup_logging
  File "/workspace/kohya_ss/library/custom_logging.py", line 6, in <module>
    from rich.theme import Theme
ModuleNotFoundError: No module named 'rich'
`

`
# tail -f workspace/logs/comfyui.log  
Traceback (most recent call last):
  File "/workspace/ComfyUI/main.py", line 66, in <module>
    import comfy.utils
  File "/workspace/ComfyUI/comfy/utils.py", line 5, in <module>
    import safetensors.torch
ModuleNotFoundError: No module named 'safetensors'
`

For Auto, I just comment the --skip-install argument to fix this, and for the others UI I have to install the modules manually (pip install..).

I noticed that there should be a /post_start.sh script that should be run, but the file is missing in the image. Maybe it comes from this ?

Best regards!

**Comment by ashleykleynhans** [comment]
There is no post start script, it checks for one and uses it if its there, but its not there and therefore not used.

This image works perfectly fine and used by hundreds of users on RunPod every single day so you are clearly doing something wrong.
