### ISSUE TITLE
Issue with latest version

### ISSUE THREAD

**Issue by shockman100** [ashleykleynhans/stable-diffusion-docker#51]
Hi 
There is an issue with the latest version on runpod. Two weeks ago was flawless.

With kohya ss this is the WD14 Captioning
looks like  DNN library is not found.

See error message:

compile configuration.
2024-03-16 16:37:41.070504: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at conv_ops_impl.h:1199 : UNIMPLEMENTED: DNN library is not found.
Traceback (most recent call last):
  File "/workspace/kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py", line 386, in <module>
    main(args)
  File "/workspace/kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py", line 290, in main
    run_batch(b_imgs)
  File "/workspace/kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py", line 180, in run_batch
    probs = model(imgs, training=False)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 5883, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.UnimplementedError: Exception encountered when calling layer 'root_conv2d' (type Conv2D).

{{function_node __wrapped__Conv2D_device_/job:localhost/replica:0/task:0/device:GPU:0}} DNN library is not found. [Op:Conv2D] name: 

Call arguments received by layer 'root_conv2d' (type Conv2D):
  • inputs=tf.Tensor(shape=(1, 448, 448, 3), dtype=float32)
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/kohya_ss/venv/bin/python3', '/workspace/kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py', '--batch_size=8', '--general_threshold=0.35', '--character_threshold=0.35', '--caption_extension=.txt', '--caption_separator=,', '--model=SmilingWolf/wd-v1-4-convnextv2-tagger-v2', '--max_data_loader_n_workers=2', '--debug', '--remove_underscore', '--frequency_tags', '/workspace/ia']' returned non-zero exit status 1.
16:37:44-127401 INFO     ...captioning done

**Comment by ashleykleynhans** [comment]
This is just a docker image, I am not the developer of the applications.
Please log an issue in the appropriate repo, in this case https://github.com/bmaltais/kohya_ss
